/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../constants/typography`; params?: Router.UnknownInputParams; } | { pathname: `/../utils/users`; params?: Router.UnknownInputParams; } | { pathname: `/../components/AppModal`; params?: Router.UnknownInputParams; } | { pathname: `/../components/GuidelineCard`; params?: Router.UnknownInputParams; } | { pathname: `/../components/BalanceCard`; params?: Router.UnknownInputParams; } | { pathname: `/../modals/PlanModal`; params?: Router.UnknownInputParams; } | { pathname: `/../modals/PlanDetailModal`; params?: Router.UnknownInputParams; } | { pathname: `/../components/DonutChart`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ahorro` | `/ahorro`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ahorros` | `/ahorros`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/categorias` | `/categorias`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/create` | `/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/movimientos` | `/movimientos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../constants/typography`; params?: Router.UnknownOutputParams; } | { pathname: `/../utils/users`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/AppModal`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/GuidelineCard`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/BalanceCard`; params?: Router.UnknownOutputParams; } | { pathname: `/../modals/PlanModal`; params?: Router.UnknownOutputParams; } | { pathname: `/../modals/PlanDetailModal`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/DonutChart`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/ahorro` | `/ahorro`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/ahorros` | `/ahorros`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/categorias` | `/categorias`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/create` | `/create`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/movimientos` | `/movimientos`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/../constants/typography${`?${string}` | `#${string}` | ''}` | `/../utils/users${`?${string}` | `#${string}` | ''}` | `/../components/AppModal${`?${string}` | `#${string}` | ''}` | `/../components/GuidelineCard${`?${string}` | `#${string}` | ''}` | `/../components/BalanceCard${`?${string}` | `#${string}` | ''}` | `/../modals/PlanModal${`?${string}` | `#${string}` | ''}` | `/../modals/PlanDetailModal${`?${string}` | `#${string}` | ''}` | `/../components/DonutChart${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/ahorro${`?${string}` | `#${string}` | ''}` | `/ahorro${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/ahorros${`?${string}` | `#${string}` | ''}` | `/ahorros${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/categorias${`?${string}` | `#${string}` | ''}` | `/categorias${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/create${`?${string}` | `#${string}` | ''}` | `/create${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/movimientos${`?${string}` | `#${string}` | ''}` | `/movimientos${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/perfil${`?${string}` | `#${string}` | ''}` | `/perfil${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../constants/typography`; params?: Router.UnknownInputParams; } | { pathname: `/../utils/users`; params?: Router.UnknownInputParams; } | { pathname: `/../components/AppModal`; params?: Router.UnknownInputParams; } | { pathname: `/../components/GuidelineCard`; params?: Router.UnknownInputParams; } | { pathname: `/../components/BalanceCard`; params?: Router.UnknownInputParams; } | { pathname: `/../modals/PlanModal`; params?: Router.UnknownInputParams; } | { pathname: `/../modals/PlanDetailModal`; params?: Router.UnknownInputParams; } | { pathname: `/../components/DonutChart`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ahorro` | `/ahorro`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ahorros` | `/ahorros`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/categorias` | `/categorias`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/create` | `/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/movimientos` | `/movimientos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; };
    }
  }
}
